<a href="https://colab.research.google.com/github/AndreSevilha02/treinando_pandas/blob/main/projeto_alunos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:

import pandas as pd

In [35]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'
pd.read_csv(url)

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

In [36]:
dados = pd.read_csv(url)
dados.head(7)

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True
5  Bruna     23    NaN     False
6   Dara     21    7.0      True

In [37]:
dados.tail(5)

      Nome  Idade  Notas  Aprovado
13   Mirla     25    9.0      True
14   Paulo     37    NaN     False
15  Mylena     29    7.0      True
16   Lucas     33    NaN     False
17   Nadia     34    8.0      True

In [38]:
dados.shape

(18, 4)

In [39]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nome      18 non-null     object
 1   Idade     18 non-null     int64
 2   Notas     12 non-null     float64
 3   Aprovado  18 non-null     bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 582.0+ bytes

In [40]:
dados['Aprovado']

0      True
1     False
2     False
3     False
4      True
5     False
6      True
7      True
8     False
9     False
10    False
11    False
12     True
13     True
14    False
15     True
16    False
17     True
Name: Aprovado, dtype: bool

In [41]:
dados.describe()

           Idade      Notas
count  18.000000  12.000000
mean   25.500000   6.800000
std     6.070662   2.204953
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000

Análise exploratória de dados

In [42]:
dados.isnull().sum()

Nome        0
Idade       0
Notas       6
Aprovado    0
dtype: int64

In [43]:
dados = dados.fillna(0)
dados

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    0.0     False
10     Daniel     21    0.0     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    0.0     False
15     Mylena     29    7.0      True
16      Lucas     33    0.0     False
17      Nadia     34    8.0      True

In [44]:
dados = dados.fillna(0)

In [45]:
dados.isnull().sum()

Nome        0
Idade       0
Notas       0
Aprovado    0
dtype: int64

In [49]:
# salvando os índices das linhas a serem removidas em uma variável
alunos_a_remover = dados.query('Nome == "Alice" | Nome == "Carlos"').index

In [50]:
dados.drop(alunos_a_remover, axis=0, inplace=True)

In [53]:
dados.head(20)

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
9       Vitor     28    0.0     False
10     Daniel     21    0.0     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    0.0     False
15     Mylena     29    7.0      True
16      Lucas     33    0.0     False
17      Nadia     34    8.0      True

In [62]:
dados.query('Aprovado == True')
alunos_aprovados = dados.query('Aprovado == True')
alunos_aprovados

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
4        Beto     21   10.0      True
6        Dara     21    7.0      True
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
15     Mylena     29    7.0      True
17      Nadia     34    8.0      True

In [65]:
dados.to_csv('alunos_aprovados.csv', index=False)

In [66]:
alunos_aprovados.replace(7.0, 8.0)

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
4        Beto     21   10.0      True
6        Dara     21    8.0      True
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
15     Mylena     29    8.0      True
17      Nadia     34    8.0      True

In [67]:
alunos_aprovados = alunos_aprovados.replace(7.0, 8.0)
alunos_aprovados

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
4        Beto     21   10.0      True
6        Dara     21    8.0      True
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
15     Mylena     29    8.0      True
17      Nadia     34    8.0      True

In [69]:
dados.to_csv('alunos_aprovados.csv', index=False, sep=';')

In [72]:
pd.read_csv('alunos_aprovados.csv', sep = ';')

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
7       Vitor     28    0.0     False
8      Daniel     21    0.0     False
9        Igor     24    4.5     False
10  Sthefanie     26    9.5      True
11      Mirla     25    9.0      True
12      Paulo     37    0.0     False
13     Mylena     29    7.0      True
14      Lucas     33    0.0     False
15      Nadia     34    8.0      True